import {AppBase,AppOptions,Asset,CameraComponentSystem,Color,ContainerHandler,ContainerResource,Entity,GSplatComponentSystem,GSplatHandler,RenderComponentSystem,TextureHandler,Vec3,createGraphicsDevice,FILLMODE_FILL_WINDOW,RESOLUTION_AUTO} from 'playcanvas';
import './style.css';
type Run={status:string;mesh?:string;splat?:string;camera?:{position:number[];target:number[]};reviewed?:boolean};
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const status=$('status'),canvas=$<HTMLCanvasElement>('view'),select=$<HTMLSelectElement>('representation');
let app:AppBase|undefined,camera:Entity,scene:Entity,urls:Record<string,string>={},run:Run,ready=false,busy=false;
let asset:Asset|undefined,object:Entity|undefined,origin=new Vec3(),yaw=0,pitch=0,scale=1;
let pointer:number|null=null,lastX=0,lastY=0;const keys=new Set<string>();
const cv=(v:number[])=>new Vec3(v[0],-v[1],-v[2]);
function validate(value:Run){if(value.status!=='reconstructed'||!value.camera)throw new Error('Esta execução ainda não produziu uma reconstrução completa.');for(const v of [value.camera.position,value.camera.target])if(!Array.isArray(v)||v.length!==3||!v.every(Number.isFinite))throw new Error('Câmera inválida no run.json.');}
function reset(){keys.clear();const p=cv(run.camera!.position),t=cv(run.camera!.target),d=t.sub(p);origin.copy(p);yaw=Math.atan2(-d.x,-d.z);pitch=Math.atan2(d.y,Math.hypot(d.x,d.z));camera.setPosition(origin);camera.setEulerAngles(pitch*180/Math.PI,yaw*180/Math.PI,0);}
async function init(){if(app)return;const device=await createGraphicsDevice(canvas,{deviceTypes:['webgl2'],antialias:true});const opts=new AppOptions();opts.graphicsDevice=device;opts.componentSystems=[CameraComponentSystem,GSplatComponentSystem,RenderComponentSystem];opts.resourceHandlers=[ContainerHandler,TextureHandler,GSplatHandler];app=new AppBase(canvas);app.init(opts);app.scene.ambientLight=new Color(1,1,1);app.setCanvasFillMode(FILLMODE_FILL_WINDOW);app.setCanvasResolution(RESOLUTION_AUTO);device.maxPixelRatio=Math.min(devicePixelRatio,2);camera=new Entity('Recovered camera');camera.addComponent('camera',{clearColor:new Color(.063,.102,.09),nearClip:.005,farClip:10000,fov:65});app.root.addChild(camera);scene=new Entity('OpenCV to viewer');scene.setEulerAngles(180,0,0);app.root.addChild(scene);app.start();addEventListener('resize',()=>app!.resizeCanvas());app.on('update',(dt:number)=>{if(!ready)return;dt=Math.min(dt,.05);const forward=Number(keys.has('w'))-Number(keys.has('s')),side=Number(keys.has('d'))-Number(keys.has('a')),vertical=Number(keys.has('e'))-Number(keys.has('q'));const length=Math.hypot(forward,side,vertical)||1;const speed=scale*dt*(keys.has('shift')?1.5:.6)/length;origin.x+=(-Math.sin(yaw)*forward+Math.cos(yaw)*side)*speed;origin.z+=(-Math.cos(yaw)*forward-Math.sin(yaw)*side)*speed;origin.y+=vertical*speed;camera.setPosition(origin);camera.setEulerAngles(pitch*180/Math.PI,yaw*180/Math.PI,0);});}
async function show(kind:string){if(busy)return;busy=true;ready=false;select.disabled=true;try{await init();const url=urls[kind];if(!url)throw new Error('Selecione o arquivo desta representação.');const next=new Asset(kind,kind==='mesh'?'container':'gsplat',{url,filename:kind==='mesh'?'scene.glb':'gaussians.ply'});await new Promise<void>((resolve,reject)=>{next.once('load',()=>resolve());next.once('error',reject);app!.assets.add(next);app!.assets.load(next);});const nextObject=kind==='mesh'?(next.resource as ContainerResource).instantiateRenderEntity():new Entity('Reconstructed splat');if(kind==='splat')nextObject.addComponent('gsplat',{asset:next});object?.destroy();if(asset){app!.assets.remove(asset);asset.unload();}asset=next;object=nextObject;scene.addChild(nextObject);reset();scale=1;ready=true;document.body.dataset.ready='true';$('badge').textContent='RECONSTRUÇÃO / INSPEÇÃO';$('title').textContent='Sala reconstruída';status.textContent='Explore a geometria. A escala e as colisões ainda precisam ser calibradas.';$('controls').textContent='Arraste para olhar · WASD para mover · Q/E para altura · Shift para acelerar';$<HTMLButtonElement>('reset').disabled=false;}catch(e){status.textContent='Não foi possível abrir o resultado: '+String(e);$('badge').textContent='RESULTADO INDISPONÍVEL';}finally{busy=false;select.disabled=!Object.keys(urls).length;}}
function options(){for(const option of Array.from(select.options))option.disabled=!urls[option.value];select.value=urls.mesh?'mesh':'splat';}
$<HTMLInputElement>('files').addEventListener('change',async(event)=>{if(busy)return;try{const files=Array.from((event.target as HTMLInputElement).files??[]),meta=files.find(f=>f.name==='run.json');if(!meta)throw new Error('Inclua run.json junto com scene.glb ou gaussians.ply.');const candidate=JSON.parse(await meta.text());validate(candidate);const next:Record<string,string>={};for(const f of files){if(f.name==='scene.glb')next.mesh=URL.createObjectURL(f);if(f.name==='gaussians.ply')next.splat=URL.createObjectURL(f);}if(!Object.keys(next).length)throw new Error('Inclua scene.glb ou gaussians.ply.');for(const u of Object.values(urls))if(u.startsWith('blob:'))URL.revokeObjectURL(u);run=candidate;urls=next;options();await show(select.value);}catch(e){status.textContent=String(e);}});
select.addEventListener('change',()=>show(select.value));$('reset').addEventListener('click',()=>reset());$('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{status.textContent='Tela cheia indisponível neste navegador.';}});
canvas.addEventListener('pointerdown',e=>{if(!ready)return;pointer=e.pointerId;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(pointer);});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==pointer)return;yaw-=(e.clientX-lastX)*.003;pitch=Math.max(-1.5,Math.min(1.5,pitch-(e.clientY-lastY)*.003));lastX=e.clientX;lastY=e.clientY;});for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,()=>{pointer=null;});
addEventListener('keydown',e=>{if(!ready||/INPUT|SELECT|TEXTAREA/.test((e.target as HTMLElement).tagName))return;const k=e.key.toLowerCase();if(['w','a','s','d','q','e','shift'].includes(k)){e.preventDefault();keys.add(k);}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>keys.clear());
try{const response=await fetch('./outputs/run.json',{cache:'no-store'});if(response.ok){const candidate=await response.json();validate(candidate);run=candidate;for(const kind of ['mesh','splat'] as const){const name=candidate[kind];if(name=== (kind==='mesh'?'scene.glb':'gaussians.ply'))urls[kind]='./outputs/'+name;}if(Object.keys(urls).length){options();await show(select.value);}}}catch{ /* Pending state remains truthful; local files can still be inspected. */ }
